# **Time Series Forcasting Project: Intelligent Weather Prediction Pipeline**

**Author:** Kishore Tirumani  
**Role:** Data Science Intern  
**Organization:** Khizex Software Solutions

**Start Date:** 07 July 2026

## Importing Necessary Libraies

In [21]:
import os
import pandas as pd
import numpy as np
import time

import psutil as ps
import sweetviz as sv
import warnings
warnings.filterwarnings("ignore")

In [2]:
%run "C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline/src/data/data_ingestion.py"

current location:  C:\Users\KISHORE\OneDrive\Desktop\Intelligent Weather Prediction Pipeline\notebooks
loading time 0.26secs
Filename: C:\Users\KISHORE\OneDrive\Desktop\Intelligent Weather Prediction Pipeline\src\data\data_ingestion.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    31    200.3 MiB    200.3 MiB           1   @profile
    32                                         def load_data(filename):
    33    200.3 MiB      0.0 MiB           1       try:
    34    200.3 MiB      0.0 MiB           1           start = time.time()
    35    209.7 MiB      9.4 MiB           1           dataset = pd.read_csv(f"{filename}.csv")
    36    209.7 MiB      0.0 MiB           1           end = time.time()
    37    209.7 MiB      0.0 MiB           1           print(f"loading time {round(end-start,2)}secs")
    38                                             except Exception as e:
    39                                                 print("faild!")
    40                                                 traceback.print_exc()
    41    209.7 MiB      0.0 MiB           1       return dataset

In [4]:
os.chdir("C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline")

from src.data import data_ingestion

In [5]:
np.set_printoptions(precision = 4 , suppress = True)
pd.set_option("display.float_format" , "{:.4f}".format)

In [6]:
weather_data = data_ingestion.load_data("open-meteo-26.61N81.26E120m")

loading time 0.21secs
Filename: C:\Users\KISHORE\OneDrive\Desktop\Intelligent Weather Prediction Pipeline\src\data\data_ingestion.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    31    216.4 MiB    216.4 MiB           1   @profile
    32                                         def load_data(filename):
    33    216.4 MiB      0.0 MiB           1       try:
    34    216.4 MiB      0.0 MiB           1           start = time.time()
    35    224.2 MiB      7.9 MiB           1           dataset = pd.read_csv(f"{filename}.csv")
    36    224.2 MiB      0.0 MiB           1           end = time.time()
    37    224.2 MiB      0.0 MiB           1           print(f"loading time {round(end-start,2)}secs")
    38                                             except Exception as e:
    39                                                 print("faild!")
    40                                                 traceback.print_exc()
    41    224.2 MiB      0.0 MiB           1       return dataset

In [13]:
cpu_percent = ps.cpu_percent(interval=1)
print(f"CPU Usage: {cpu_percent}%")

CPU Usage: 15.3%

In [22]:
weather_data.head(3)

,time,temperature_2m (°C),relative_humidity_2m (%),rain (mm),soil_temperature_0_to_7cm (°C),wind_speed_100m (km/h),surface_pressure (hPa),pressure_msl (hPa),is_day ()
0,2020-01-01T00:00,5.8000,93,0.0000,8.3000,15.1000,1004.5000,1019.4000,0
1,2020-01-01T01:00,5.7000,93,0.0000,8.0000,14.5000,1004.4000,1019.3000,0
2,2020-01-01T02:00,6.0000,93,0.0000,7.8000,12.7000,1004.6000,1019.4000,0

In [10]:
weather_data.tail(3)

,time,temperature_2m (°C),relative_humidity_2m (%),rain (mm),soil_temperature_0_to_7cm (°C),wind_speed_100m (km/h),surface_pressure (hPa),pressure_msl (hPa),is_day ()
52605,2025-12-31T21:00,10.1000,96,0.0000,11.9000,8.9000,999.8000,1014.4000,0
52606,2025-12-31T22:00,9.3000,98,0.0000,11.4000,8.7000,999.9000,1014.5000,0
52607,2025-12-31T23:00,9.0000,100,0.0000,11.5000,12.1000,999.8000,1014.4000,0

In [20]:
weather_data.sample(n=500).head(3)

,time,temperature_2m (°C),relative_humidity_2m (%),rain (mm),soil_temperature_0_to_7cm (°C),wind_speed_100m (km/h),surface_pressure (hPa),pressure_msl (hPa),is_day ()
27115,2023-02-03T19:00,16.4000,72,0.0000,18.1000,24.8000,1000.4000,1014.6000,0
4920,2020-07-24T00:00,26.8000,92,0.0000,28.5000,16.3000,989.3000,1002.9000,0
46757,2025-05-02T05:00,24.6000,66,0.0000,26.6000,28.8000,995.1000,1008.9000,1

In [12]:
print("Shape of the dataset: ",weather_data.shape)
print("Size of the dataset: ",weather_data.size)

Shape of the dataset:  (52608, 9)
Size of the dataset:  473472

In [14]:
print("Memory Usage of the dataset is : ", weather_data.memory_usage(),end = "\n")

Memory Usage of the dataset is :  Index                                132
time                              420864
temperature_2m (°C)               420864
relative_humidity_2m (%)          420864
rain (mm)                         420864
soil_temperature_0_to_7cm (°C)    420864
wind_speed_100m (km/h)            420864
surface_pressure (hPa)            420864
pressure_msl (hPa)                420864
is_day ()                         420864
dtype: int64

In [17]:
weather_data.columns

Index(['time', 'temperature_2m (°C)', 'relative_humidity_2m (%)', 'rain (mm)',
       'soil_temperature_0_to_7cm (°C)', 'wind_speed_100m (km/h)',
       'surface_pressure (hPa)', 'pressure_msl (hPa)', 'is_day ()'],
      dtype='object')

In [15]:
d = {"Column": weather_data.columns, "Dtype" : weather_data.dtypes}
data_types_df = pd.DataFrame(d)
index = [""]*len(data_types_df)
data_types_df.index = index
data_types_df

                          Column    Dtype
                            time   object
             temperature_2m (°C)  float64
        relative_humidity_2m (%)    int64
                       rain (mm)  float64
  soil_temperature_0_to_7cm (°C)  float64
          wind_speed_100m (km/h)  float64
          surface_pressure (hPa)  float64
              pressure_msl (hPa)  float64
                       is_day ()    int64

In [16]:
os.chdir("C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline/reports")
start = time.time()
report = sv.analyze(weather_data)
report.show_html("weather_data_basic_report.html")
end = time.time()
print(f"TIme taken: {round(end-start,2)}sec")
cpu_percent = ps.cpu_percent(interval=1)
print(f"CPU Usage: {cpu_percent}%")

                                             |                                             | [  0%]   00:00 ->…

Report weather_data_basic_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.
TIme taken: 17.47sec
CPU Usage: 44.5%