### importing necessary libraries

In [1]:
import os
import pandas as pd
import numpy as np
import joblib

### loaing installed python packages

In [2]:
from src.utils.config import INTERIM,PROCESSED,ROOT_DIR,CLN_DATA_FILE,ARTIFACTS
from src.features.feature_encoding import encode_features
from scripts.features.make_features import add_encode_features

Lahore Real Estate Price Prediction Pipeline

In [3]:
lohore_dataset = pd.read_csv(ROOT_DIR/INTERIM/CLN_DATA_FILE)
lohore_dataset.head(2)

,Title,Location,Type,Price,Area,Bedrooms,Bathrooms,Purpose,Kitchens,Store_Rooms,...,Study_Room,Drawing_Room,Dining_Room,Lawn_Garden,Swimming_Pool,Electricity_Backup,Lounge_Sitting_Room,Area_sqft,Price_PKR,Location_Normalized
0,ACTUALLY 25 MARLA DOUBLE UNIT LUXURIOUS & GRAC...,"DHA Phase 6 - Block F, DHA Phase 6, DHA Defenc...",House,8.15 Crore,1 Kanal,6.0,7.0,For Sale,3,2,...,True,True,True,True,True,True,True,4500.0,81500000.0,DHA Phase 6
1,3 Years Installment Plan Luxury Brand New Hous...,"Park View City, Lahore, Punjab",House,1.5 Crore,5 Marla,4.0,5.0,For Sale,2,1,...,False,True,True,True,False,True,True,1125.0,15000000.0,Lahore

In [4]:
lohore_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17729 entries, 0 to 17728
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Title                17729 non-null  object
 1   Location             17729 non-null  object
 2   Type                 17729 non-null  object
 3   Price                17729 non-null  object
 4   Area                 17729 non-null  object
 5   Bedrooms             17729 non-null  float64
 6   Bathrooms            17729 non-null  float64
 7   Purpose              17729 non-null  object
 8   Kitchens             17729 non-null  int64
 9   Store_Rooms          17729 non-null  int64
 10  Servant_Quarters     17729 non-null  int64
 11  Furnished            17729 non-null  bool
 12  Gym                  17729 non-null  bool
 13  Study_Room           17729 non-null  bool
 14  Drawing_Room         17729 non-null  bool
 15  Dining_Room          17729 non-null  bool
 16  Lawn_Garden          17729 non-null  bool
 17  Swimming_Pool        17729 non-null  bool
 18  Electricity_Backup   17729 non-null  bool
 19  Lounge_Sitting_Room  17729 non-null  bool
 20  Area_sqft            17729 non-null  float64
 21  Price_PKR            17729 non-null  float64
 22  Location_Normalized  17729 non-null  object
dtypes: bool(9), float64(4), int64(3), object(7)
memory usage: 2.0+ MB

- **Dataset have Object(Categorical) features.we need to encode them for modeling.**

In [5]:
lohore_dataset = add_encode_features(lohore_dataset)

In [6]:
X_train, X_test, y_train, y_test, target_encoder, encoder = encode_features(lohore_dataset)

In [7]:
y_train

13063     52500000.0
3099      19000000.0
14479    105000000.0
5099      26500000.0
12706     65000000.0
            ...
11284     22000000.0
11964     21500000.0
5390      28500000.0
860       97500000.0
15795     97000000.0
Name: Price_PKR, Length: 14183, dtype: float64

In [8]:
X_train.head(2)

,Title,Location,Type,Price,Area,Bedrooms,Bathrooms,Purpose,Kitchens,Store_Rooms,...,Swimming_Pool,Electricity_Backup,Lounge_Sitting_Room,Area_sqft,Location_Normalized,bedroom_bath_ratio,log_area_sqft,price_per_sqft,Type_House,Purpose_For Sale
13063,Reasonably-Priced 10 Marla House In Paragon Ci...,"Paragon City - Imperial 1 Block, Paragon City,...",House,5.25 Crore,10 Marla,4.0,5.0,For Sale,0,0,...,0,0,0,2250.0,3.407921e+07,0.8,7.719130,23333.333333,1.0,1.0
3099,5 Marla House For Sale In BB Block Sector D Ba...,"Bahria Town - Block BB, Bahria Town - Sector D...",House,1.9 Crore,5 Marla,3.0,5.0,For Sale,2,0,...,0,1,0,1125.0,2.323606e+07,0.6,7.026427,16888.888889,1.0,1.0

In [9]:
X_train.columns

Index(['Title', 'Location', 'Type', 'Price', 'Area', 'Bedrooms', 'Bathrooms',
       'Purpose', 'Kitchens', 'Store_Rooms', 'Servant_Quarters', 'Furnished',
       'Gym', 'Study_Room', 'Drawing_Room', 'Dining_Room', 'Lawn_Garden',
       'Swimming_Pool', 'Electricity_Backup', 'Lounge_Sitting_Room',
       'Area_sqft', 'Location_Normalized', 'bedroom_bath_ratio',
       'log_area_sqft', 'price_per_sqft', 'Type_House', 'Purpose_For Sale'],
      dtype='object')

In [10]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3546 entries, 11799 to 12725
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Title                3546 non-null   object
 1   Location             3546 non-null   object
 2   Type                 3546 non-null   object
 3   Price                3546 non-null   object
 4   Area                 3546 non-null   object
 5   Bedrooms             3546 non-null   float64
 6   Bathrooms            3546 non-null   float64
 7   Purpose              3546 non-null   object
 8   Kitchens             3546 non-null   int64
 9   Store_Rooms          3546 non-null   int64
 10  Servant_Quarters     3546 non-null   int64
 11  Furnished            3546 non-null   int64
 12  Gym                  3546 non-null   int64
 13  Study_Room           3546 non-null   int64
 14  Drawing_Room         3546 non-null   int64
 15  Dining_Room          3546 non-null   int64
 16  Lawn_Garden          3546 non-null   int64
 17  Swimming_Pool        3546 non-null   int64
 18  Electricity_Backup   3546 non-null   int64
 19  Lounge_Sitting_Room  3546 non-null   int64
 20  Area_sqft            3546 non-null   float64
 21  Location_Normalized  3546 non-null   float64
 22  bedroom_bath_ratio   3546 non-null   float64
 23  log_area_sqft        3546 non-null   float64
 24  price_per_sqft       3546 non-null   float64
 25  Type_House           3546 non-null   float64
 26  Purpose_For Sale     3546 non-null   float64
dtypes: float64(9), int64(12), object(6)
memory usage: 775.7+ KB

- **We have encoded features,So we need to drop origianl features**

In [11]:
#droping original features
X_train.drop(columns = ['Title', 'Location', 'Type', 'Price', 'Area', 'Purpose'],inplace = True)
X_test.drop(columns = ['Title', 'Location', 'Type', 'Price', 'Area', 'Purpose'],inplace = True)

In [12]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14183 entries, 13063 to 15795
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Bedrooms             14183 non-null  float64
 1   Bathrooms            14183 non-null  float64
 2   Kitchens             14183 non-null  int64
 3   Store_Rooms          14183 non-null  int64
 4   Servant_Quarters     14183 non-null  int64
 5   Furnished            14183 non-null  int64
 6   Gym                  14183 non-null  int64
 7   Study_Room           14183 non-null  int64
 8   Drawing_Room         14183 non-null  int64
 9   Dining_Room          14183 non-null  int64
 10  Lawn_Garden          14183 non-null  int64
 11  Swimming_Pool        14183 non-null  int64
 12  Electricity_Backup   14183 non-null  int64
 13  Lounge_Sitting_Room  14183 non-null  int64
 14  Area_sqft            14183 non-null  float64
 15  Location_Normalized  14183 non-null  float64
 16  bedroom_bath_ratio   14183 non-null  float64
 17  log_area_sqft        14183 non-null  float64
 18  price_per_sqft       14183 non-null  float64
 19  Type_House           14183 non-null  float64
 20  Purpose_For Sale     14183 non-null  float64
dtypes: float64(9), int64(12)
memory usage: 2.4 MB

### Saaving datasets & Encoders

In [13]:
os.chdir(ROOT_DIR/PROCESSED)
X_train.to_csv("X_train.csv",index = False)
X_test.to_csv("X_test.csv",index = False)
y_test.to_csv("y_test.csv",index = False)
y_train.to_csv("y_train.csv",index = False)

In [14]:
os.chdir(ROOT_DIR/ARTIFACTS)
joblib.dump(target_encoder, "target_encoder.pkl")
joblib.dump(encoder, "onehot_encoder.pkl")
print("file Saved Successfully!")

file Saved Successfully!